project:
  type: website
  output-dir: docs

website:
  title: "Dirceu S. Reis Jr."
  page-footer: "This website was created with [Quarto](https://quarto.org/)."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: projects/index.qmd
        text: Projects
      - href: short_courses/index.qmd
        text: Short Courses
      - href: blog/index.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme:
      - united
    css: styles.css
    toc: true

editor: visual

